# os.PathLike is a public standard-library type with dynamic exports.
# noinspection PyProtectedMember
from os import PathLike
from collections.abc import Sequence

SAMPLE_WIDTH: int
SAMPLE_HEIGHT: int
MAX_SOURCE_PIXELS: int
MAX_ENCODED_BYTES: int

def validate_buffer(pixels: bytes, width: int, height: int, mode: str) -> None: ...
def decode_path(path: str | PathLike[str]) -> tuple[int, int, str, bytes]: ...
def decode_bytes(data: bytes) -> tuple[int, int, str, bytes]: ...
def sample_path(path: str | PathLike[str]) -> tuple[int, int, bytes]: ...
def sample_buffer(pixels: bytes, width: int, height: int, mode: str) -> bytes: ...
def composite_rgb(pixels: bytes, width: int, height: int, mode: str) -> bytes: ...
def render(commands: Sequence[Sequence[int]], palette: Sequence[Sequence[int]]) -> bytes: ...
def encode_png(pixels: bytes, width: int, height: int) -> bytes: ...
def plan_strokes(
    pixels: bytes, palette: Sequence[Sequence[int]], colors: Sequence[int], budget: int
) -> list[list[int]]: ...
