"""Protocol limits and default resource budgets."""

MAX_NAME_LENGTH = 21
MAX_CHAT_LENGTH = 100
MIN_CHAT_INTERVAL = 1.0
DEFAULT_EVENT_BUFFER = 512
DEFAULT_CHAT_QUEUE_SIZE = 128
DEFAULT_CONNECT_TIMEOUT = 20.0
MAX_DRAWING_HISTORY = 100_000
MAX_HINT_LENGTH = 4096
MAX_MATCHMAKER_RESPONSE = 4096
MAX_SOCKET_PAYLOAD = 1_048_576
MIN_BRUSH_DIAMETER = 4
MAX_BRUSH_DIAMETER = 40
DEFAULT_BASE_URL = 'https://skribbl.io'
AVATAR_COLOR_VARIANTS = 28
AVATAR_EYE_VARIANTS = 57
AVATAR_MOUTH_VARIANTS = 51
ORDINARY_AVATAR_SPECIAL = -1
